### ISSUE TITLE
ES is getting crashed after doing search query for knn

### ISSUE THREAD

**Issue by sarita05** [opendistro-for-elasticsearch/k-NN#95] opened 2020-04-17 07:17 UTC
For details : https://discuss.opendistrocommunity.dev/t/elastic-search-is-getting-crashed-after-running-knn-query/2601
I have used Ubuntu OS 16.04 version.

I have followed doc but there is some inconsistency. 
1. We are creating index with other name and putting data in another ( myindex and my_index). 
https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md
2. We are having mapping fields as my_vector1, my_vector2 and my_vector3 but inserting data in my_vector
https://github.com/opendistro-for-elasticsearch/k-NN/blob/development/README.md#java-native-library-usage

My ES is getting crashed. There is no error log but found a file named as hs_err_pid12902.log under /var/log/elasticsearch directory.

Problematic frame:
C [libKNNIndexV1_7_3_6.so+0xcb10a] _GLOBAL__sub_I_distcomp_sparse_scalar_fast.cc+0x2a
ES get crashed sometimes with GET, few times during data insertion and mostly with search.

We have tried with below mentioned version but issue still persist.
-	1.3.0, 1.4.0 and 1.6.0 on Ubuntu. ( having glibc 3.4.22 version dependency)
-	Docker installation with 1.6.0

**Comment by vamshin** [comment] 2020-04-17 22:55
Hi @sarita05 ,
thanks for pointing the errors.

> We are creating index with other name and putting data in another ( myindex and my_index).
> https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md

Corrected https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md

> We are having mapping fields as my_vector1, my_vector2 and my_vector3 but inserting data in my_vector
https://github.com/opendistro-for-elasticsearch/k-NN/blob/development/README.md#java-native-library-usage

Please refer the master branch https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/README.md

> C [libKNNIndexV1_7_3_6.so+0xcb10a] _GLOBAL__sub_I_distcomp_sparse_scalar_fast.cc+0x2a
ES get crashed sometimes with GET, few times during data insertion and mostly with search.

Looks like library is not compatible with the OS. Can you can try building library locally . Instructions mentioned in this issue https://github.com/opendistro-for-elasticsearch/k-NN/issues/4 

Do you see the same error with Docker1.6 as well?

**Comment by sarita05** [comment] 2020-04-20 04:52
> Hi @sarita05 ,
> thanks for pointing the errors.
> 
> > We are creating index with other name and putting data in another ( myindex and my_index).
> > https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md
> 
> Corrected https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md
> 
> > We are having mapping fields as my_vector1, my_vector2 and my_vector3 but inserting data in my_vector
> > https://github.com/opendistro-for-elasticsearch/k-NN/blob/development/README.md#java-native-library-usage
> 
> Please refer the master branch https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/README.md
> 
> > C [libKNNIndexV1_7_3_6.so+0xcb10a] _GLOBAL__sub_I_distcomp_sparse_scalar_fast.cc+0x2a
> > ES get crashed sometimes with GET, few times during data insertion and mostly with search.
> 
> Looks like library is not compatible with the OS. Can you can try building library locally . Instructions mentioned in this issue #4
> 
> Do you see the same error with Docker1.6 as well?
=========================================
Do you see the same error with Docker1.6 as well?
- Yes, I am facing same issue with Docker1.6 as well. Link that I have followed is :
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/
and used SAMPLE DOCKER COMPOSE FILE.

**Comment by sarita05** [comment] 2020-04-20 04:55
Corrected https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md
-- It needs to be corrected even from dimension perspective.
All fields have dimension defined as 2  but later you are inserting data more than that. It will shout with error.
For example POST my_index/_doc/4
{
  "my_vector2" : [6.5, 7.5, 8.5]
}
we have used three values, It should be as per dimension. You can put a note there that defined dimension needs to be inline with values.

**Comment by sarita05** [comment] 2020-04-24 04:38
Do we have any update on this ?

**Comment by sarita05** [comment] 2020-04-24 16:11
Instead of throwing an exception, why it is crashing ES. 
I am using docker image ( no dependency) but still ES is getting crashed after invoking search query. 

POST my_index/_search
{
  "size" : 2,
  "query": {
    "knn": {
      "my_vector1": {
        "vector": [3, 4],
        "k": 2
      }
    }
  }
}

**Comment by vamshin** [comment] 2020-04-24 16:49
hi @sarita05 ,

Apologies for the delay.  Seems to be library incompatible issues.

We will try to reproduce the issue and come back.

**Comment by jmazanec15** [comment] 2020-04-24 17:37
Hi @sarita05,

I am trying to reproduce the crash.

I am having a little trouble following the Elasticsearch calls you made that led to the crash. Could you please list, in order, the API calls that you made (including the request bodies) in your workflow that generated a crash? Then I can try to better debug/reproduce the crash.

**Comment by sarita05** [comment] 2020-05-03 07:24
> Hi @sarita05,
> 
> I am trying to reproduce the crash.
> 
> I am having a little trouble following the Elasticsearch calls you made that led to the crash. Could you please list, in order, the API calls that you made (including the request bodies) in your workflow that generated a crash? Then I can try to better debug/reproduce the crash.

**Comment by sarita05** [comment] 2020-05-03 07:27
I found that someone updated the document  for docker image. Earlier it was showing compatible OS as Ubuntu and CentOS but now its showing only CentOS.

I have tried the docker image on CentOS 7.0 and its working fine there. ES is not getting crash after get query to retrieve the data from knn_vector.

**Comment by sarita05** [comment] 2020-05-03 07:30
> Hi @sarita05,
> 
> I am trying to reproduce the crash.
> 
> I am having a little trouble following the Elasticsearch calls you made that led to the crash. Could you please list, in order, the API calls that you made (including the request bodies) in your workflow that generated a crash? Then I can try to better debug/reproduce the crash.

--> I found that document has been updated and now it containing only OS version CentOS 7.0 Earlier it was Ubuntu and CentOS. I have tried docker image on CentOS 7.0 and found that its working fine. ES is not getting crashed with search query. I have tried docker image on Ubuntu but issue still exists.

-- > Just followed https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/RFC.md
Usage --> Creating K-NN index , Indexing vectors and Querying K-Nearest Neighbors.
ES is getting crash using following query (Querying K-Nearest Neighbors):

POST my_index/_search
{
  "size" : 2,
  "query": {
    "knn": {
      "my_vector1": {
        "vector": [3, 4],
        "k": 2
      }
    }
  }
}

**Comment by sarita05** [comment] 2020-05-03 18:47
Query Used :

curl -X PUT 'http://<server_name>:9200/myindex' -H 'Content-Type: application/json' -d '
{
  "settings": {
    "index": {
            "knn": true
        }
  },
  "mappings": {
    "properties": {
      "msg": {
        "type": "knn_vector",
        "dimension": 5
      }
    }
  }
}'

curl -X POST "http://<server_name>:9200/myindex/_doc/1" -H 'Content-Type: application/json' -d'
{
"msg" : [1.5, 2.5, 4.5, 6.5,7.5]
}
'

curl -X POST "http://<server_name>:9200/myindex/_doc/2" -H 'Content-Type: application/json' -d'
{
"msg" : [1.5, 2.5, 8.5, 9.5,7.5]
}
'

curl -X POST "http://<erver_name>:9200/myindex/_search" -H 'Content-Type: application/json' -d'
{"size" : 10,
 "query": {
  "knn": {
   "msg": {
     "vector": [3.3, 4.4,5.5,6.6,7.7],
     "k": 2
   }
  }
 }
}
'

**Comment by jmazanec15** [comment] 2020-05-05 21:39
Still trying to reproduce the issue. Was unable to with the following steps

1. Launched m5.xlarge Ubuntu Server 16.04 LTS (HVM), SSD Volume Type instance

2. Installed dockerd and docker-compose

3. Adjusted vm.max_map_count=262144 in system /etc/sysctl.conf

4. Copied this [docker-compose](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file) and switched `version` to `2`

5. Ran `docker-compose up`

6. Ran the following commands:
```
ubuntu@:~$ curl -X PUT 'https://localhost:9200/myindex'  -u admin:admin --insecure -H 'Content-Type: application/json' -d '
> {
> "settings": {
> "index": {
> "knn": true
> }
> },
> "mappings": {
> "properties": {
> "msg": {
> "type": "knn_vector",
> "dimension": 5
> }
> }
> }
> }'
{"acknowledged":true,"shards_acknowledged":true,"index":"myindex"}

ubuntu@:~$ curl -X POST "https://localhost:9200/myindex/_doc/1"  -u admin:admin --insecure -H 'Content-Type: application/json' -d'
> {
> "msg" : [1.5, 2.5, 4.5, 6.5,7.5]
> }
> '
{"_index":"myindex","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":1}

ubuntu@:~$ curl -X POST "https://localhost:9200/myindex/_doc/2"  -u admin:admin --insecure -H 'Content-Type: application/json' -d'
> {
> "msg" : [1.5, 2.5, 8.5, 9.5,7.5]
> }
> '
{"_index":"myindex","_type":"_doc","_id":"2","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":1,"_primary_term":1}
ubuntu@:~$ curl -X POST "https://localhost:9200/myindex/_search"  -u admin:admin --insecure -H 'Content-Type: application/json' -d'
> {"size" : 10,
> "query": {
> "knn": {
> "msg": {
> "vector": [3.3, 4.4,5.5,6.6,7.7],
> "k": 2
> }
> }
> }
> }
> '
{"took":206,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":0.2624194,"hits":[{"_index":"myindex","_type":"_doc","_id":"1","_score":0.2624194,"_source":
{
"msg" : [1.5, 2.5, 4.5, 6.5,7.5]
}
},{"_index":"myindex","_type":"_doc","_id":"2","_score":0.1686482,"_source":
{
"msg" : [1.5, 2.5, 8.5, 9.5,7.5]
}
}]}}
```

@sarita05 how does your configuration differ from this?

**Comment by vamshin** [comment] 2020-05-29 22:11
Closing the issue since not active

**Closed as completed by vamshin** 2020-05-29 22:11 UTC

**Comment by sudo-datluu** [comment] 2020-08-05 05:28
Hello, after i POST new knn vector, the whole ES system get crashed, 
The message said this:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f9a98ef6f89, pid=1, tid=271
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libKNNIndexV1_7_3_6.so+0x1a1f89]  float std::generate_canonical<float, 24ul, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> >(std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&)+0x1c9
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /usr/share/elasticsearch/core.1)
#
# An error report file with more information is saved as:
# logs/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f9b2944dbc7]
```

I tried to restart with the [docker-compose](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file) file, or run with a new container, index again, but it failed to start the ES system and the error kept reproducing.

**Comment by sudo-datluu** [comment] 2020-08-05 05:40
When i check with the `java --version` it currently used java 11:
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode)
```
And after i created .so library in[ #4](https://github.com/opendistro-for-elasticsearch/k-NN/issues/4), what should i do further more to replace the old .so library running in the odfe?

**Comment by jmazanec15** [comment] 2020-09-10 19:14
Hi @datluu-dev 

Sorry for the delayed response.

Could you follow these steps? https://github.com/opendistro-for-elasticsearch/k-NN/issues/220#issuecomment-690646988

Jack

**Comment by sudo-datluu** [comment] 2020-10-05 02:55
Hi there, thank you, for your support, i have installed latest version [1.10.1](https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/376) and it worked magnificently
